CREATE TABLE post_feed(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    id_usurio BIGINT(20) NOT NULL;
	FOREIGN KEY (id_usuario) REFERENCES usuario(id)
)ENGINE=innoDB DEFAULT CHARSET=utf8;
