CREATE TABLE usuario(
    nomeUsuario VARCHAR(100) NOT NULL,
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	login VARCHAR(20) NOT NULL,
	senha VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	data_cadastro DATE NOT NULL
)ENGINE=innoDB DEFAULT CHARSET=utf8;


